name: enthrirhs
description: Enţrirç (Ithkuil Helper)
publish_to: 'none'

version: 0.3.0-rc1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: 6.1.1
  drift: 2.15.0
  path_provider: 2.1.2
  path: 1.9.0
  provider: 6.1.1
  sqlite3_flutter_libs: ^0.5.19+1
  sqlite3: 2.3.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.18+3
  package_info_plus: 5.0.1
  vector_graphics: ^1.1.9+1
  prompt_dialog: ^1.0.15
  share_plus: ^7.2.1

dev_dependencies:
  flutter_lints: 3.0.1
  drift_dev: 2.15.0
  build_runner: 2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/icons_compiled/discord.svg.vec
    - assets/icons_compiled/github.svg.vec
    - assets/icons_compiled/reddit.svg.vec
    - assets/icons_compiled/telegram.svg.vec
    - assets/icons_compiled/tencentqq.svg.vec
    - assets/icons_compiled/logo.svg.vec
    # Material Icons
    - assets/icons_compiled/airwave.svg.vec
    - assets/icons_compiled/communities.svg.vec
    - assets/icons_compiled/jump_to_element.svg.vec
    - assets/icons_compiled/line_start_circle.svg.vec
    - assets/icons_compiled/quick_reference_all.svg.vec
    - assets/icons_compiled/shapes.svg.vec
    - assets/icons_compiled/steppers.svg.vec
    - assets/icons_compiled/transition_fade.svg.vec

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
