name: Build
on: [push]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'
          channel: 'stable'
      - run: flutter pub get
      - run: dart run build_runner build
      - run: dart run vector_graphics_compiler --input-dir assets/icons --out-dir assets/icons_compiled
      - run: flutter build apk --split-per-abi
      - uses: actions/upload-artifact@v3
        with:
          name: android
          path: build/app/outputs/flutter-apk/

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'
          channel: 'stable'
      - run: flutter pub get
      - run: dart run build_runner build
      - run: dart run vector_graphics_compiler --input-dir assets/icons --out-dir assets/icons_compiled
      - run: flutter build web
      - uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web/

